In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

### Creating Tensor

In [6]:
# 0D tensor is called scaler
scaler = torch.tensor(7)

print('Scaler:', scaler)
print('Scaler size:', scaler.shape)
print('Scaler dimention:', scaler.ndim)

Scaler: tensor(7)
Scaler size: torch.Size([])
Scaler dimention: 0


()

In [7]:
# 1D tensor is called vector
vector = torch.tensor([1, 2, 3, 4])

print('vector:', vector)
print('vector size:', vector.shape)
print('vector dimention:', vector.ndim)

vector: tensor([1, 2, 3, 4])
vector size: torch.Size([4])
vector dimention: 1


In [9]:
# 2D tensor is called matrix
matrix = torch.tensor([[1, 2, 3], [2, 3, 4]])

print('matrix:\n', matrix)
print('matrix size:', matrix.shape)
print('matrix dimention:', matrix.ndim)

matrix:
 tensor([[1, 2, 3],
        [2, 3, 4]])
matrix size: torch.Size([2, 3])
matrix dimention: 2


In [10]:
# 3D tensor
tensor = torch.tensor([[[1, 2, 3], [10, 45, 56]], [[12, 34, 55], [23, 56, 67]]])

print('tensor:\n', tensor)
print('tensor size:', tensor.shape)
print('tensor dimention:', tensor.ndim)

tensor:
 tensor([[[ 1,  2,  3],
         [10, 45, 56]],

        [[12, 34, 55],
         [23, 56, 67]]])
tensor size: torch.Size([2, 2, 3])
tensor dimention: 3


#### GPU Acceleration

In [11]:
if torch.cuda.is_available():
  gpu_matrix = matrix.to('cuda')
  print(gpu_matrix)
else:
  print('GPU Acceleration is not available')

tensor([[1, 2, 3],
        [2, 3, 4]], device='cuda:0')


In [15]:
# tensor properties

print('size:', matrix.size())
print('dimension:', matrix.ndim)

print('GPU:', matrix.device)
print('GPU:', gpu_matrix.device)

print('Is matrix run on GPU:', matrix.is_cuda)
print('Is matrix run on GPU:', gpu_matrix.is_cuda)

print('Number of element in tensor:', matrix.numel())

size: torch.Size([2, 3])
dimension: 2
GPU: cpu
GPU: cuda:0
Is matrix run on GPU: False
Is matrix run on GPU: True
Number of element in tensor: 6
