In [23]:
import torch

## Accessing tensor
```
tensor_name[row, col]
```

In [24]:
# Create a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [56, 32, 21]])

### 1. Indexing

In [25]:
# access 0th row and 1st column element
tensor[0, 1]

tensor(2)

In [26]:
# access 1st row
tensor[1]

tensor([4, 5, 6])

In [27]:
# access the 1st column
tensor[:, 1]

tensor([ 2,  5, 32])

### 2. Slicing

In [28]:
print(tensor)
# slice 0th, 1st row and 1st, 2nd column
tensor[:2, 1:3]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [56, 32, 21]])


tensor([[2, 3],
        [5, 6]])

In [29]:
# access element in step 2
# access 0th, 2nd row and all column
tensor[::2]

tensor([[ 1,  2,  3],
        [56, 32, 21]])

In [30]:
# access all row and 0th, 2nd column
tensor[:, ::2]

tensor([[ 1,  3],
        [ 4,  6],
        [56, 21]])

In [31]:
# access 1st row and 1st, 2nd column only
tensor[1, 1:3]

tensor([5, 6])

### Fancy Indexing

In [32]:
tensor

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [56, 32, 21]])

In [33]:
# access 0th row, 0th column and 2th row, 2th column
# (0, 0) ---> 1
# (2, 2) ---> 21
tensor[[0, 2], [0, 2]]

tensor([ 1, 21])

### Boolean Indexing

In [34]:
mask = tensor > 30
print(mask)
print(tensor[mask])

tensor([[False, False, False],
        [False, False, False],
        [ True,  True, False]])
tensor([56, 32])


### Changing Tensor values

In [35]:
print('Before', tensor)

# Change 0th row, 1th column
tensor[0, 1] = 33

print('After', tensor)

Before tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [56, 32, 21]])
After tensor([[ 1, 33,  3],
        [ 4,  5,  6],
        [56, 32, 21]])


In [38]:
# Change 1st row value
tensor[1] = torch.tensor([12, 45, 76])
print(tensor)

tensor([[ 1, 33,  3],
        [12, 45, 76],
        [56, 32, 21]])


In [39]:
# Change 1st column
tensor[:, 1] = torch.tensor([99, 55, 21])
print(tensor)

tensor([[ 1, 99,  3],
        [12, 55, 76],
        [56, 21, 21]])


### Select indices using function
0 for row<br>
1 for column

In [41]:
indices = torch.tensor([0, 2])
selected_row = torch.index_select(tensor, 0, indices)
selected_row

tensor([[ 1, 99,  3],
        [56, 21, 21]])

In [43]:
selected_column = torch.index_select(tensor, 1, indices)
selected_column

tensor([[ 1,  3],
        [12, 76],
        [56, 21]])