In [1]:
import torch
import torch.nn as nn

In [2]:
# create a 4x4x1 dummy image
image = torch.tensor([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 4, 5, 3],
                      [0, 4, 3, 1]], dtype=torch.float32).unsqueeze(0)
image

tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.],
         [9., 4., 5., 3.],
         [0., 4., 3., 1.]]])

In [3]:
image.shape

torch.Size([1, 4, 4])

In [4]:
# MaxPooling
down = nn.MaxPool2d(kernel_size=(2, 2), stride=2, padding=0)(image)
down

tensor([[[6., 8.],
         [9., 5.]]])

In [5]:
# AvgPooling
avg = nn.AvgPool2d(kernel_size=(3, 3), stride=1, padding=0)(image)
avg

tensor([[[4.6667, 4.6667],
         [4.7778, 4.5556]]])

In [6]:
# Global average pooling
globalAvg = nn.AdaptiveAvgPool2d((1, 1))(image)
globalAvg.squeeze()

tensor(4.0625)

In [7]:
# Down sampling using conv layer
convDown = nn.Conv2d(1, 1, kernel_size=(2, 2), stride=2, padding=0)(image)
convDown.squeeze()

tensor([[-2.0768, -2.9973],
        [-2.9686, -1.1295]], grad_fn=<SqueezeBackward0>)