# Basic

In [ ]:
import torch
import torch.nn.functional as F

In [ ]:
# Create dummy image
image = torch.tensor([[1, 2],
                      [3, 4]], dtype=torch.float32).unsqueeze(0).unsqueeze(0)
image.shape

torch.Size([1, 1, 2, 2])

In [ ]:
# Upsampling using interpolation with bilinear method
image_bl = F.interpolate(image, scale_factor=2, mode='bilinear')
image_bl.squeeze(0)

tensor([[[1.0000, 1.2500, 1.7500, 2.0000],
         [1.5000, 1.7500, 2.2500, 2.5000],
         [2.5000, 2.7500, 3.2500, 3.5000],
         [3.0000, 3.2500, 3.7500, 4.0000]]])

In [ ]:
# Upsampling using interpolation with nearest method
image_nn = F.interpolate(image, scale_factor=2, mode='nearest')
image_nn.squeeze(0)

tensor([[[1., 1., 2., 2.],
         [1., 1., 2., 2.],
         [3., 3., 4., 4.],
         [3., 3., 4., 4.]]])

In [ ]:
# Upsampling with CNN based layer or trainable layer
image_up = torch.nn.ConvTranspose2d(1, 1, kernel_size=(2, 2), stride=2, padding=0)(image)
image_up.squeeze(0)

tensor([[[ 0.4934,  0.2153,  0.6970,  0.1408],
         [ 0.5726, -0.1774,  0.8554, -0.6447],
         [ 0.9006,  0.0662,  1.1042, -0.0083],
         [ 1.1382, -1.1120,  1.4210, -1.5793]]], grad_fn=<SqueezeBackward1>)

# Transposed Convolution

In [1]:
import torch
import torch.nn as nn

In [42]:
x = torch.tensor([[0, 1], [2, 3]], dtype=torch.float32)
k = torch.tensor([[0, 1], [2, 3]], dtype=torch.float32)

In [43]:
x = x.view(1, 1, 2, 2)
k = k.view(1, 1, 2, 2)

In [44]:
x

tensor([[[[0., 1.],
          [2., 3.]]]])

In [45]:
# Basic Operation
up_train = nn.ConvTranspose2d(1, 1, kernel_size=2, stride=1, padding=0, bias=False)
up_train.weight.data = k

y = up_train(x)
print(y)
print(up_train.weight.data)

tensor([[[[ 0.,  0.,  1.],
          [ 0.,  4.,  6.],
          [ 4., 12.,  9.]]]], grad_fn=<ConvolutionBackward0>)
tensor([[[[0., 1.],
          [2., 3.]]]])


In [46]:
# With padding 1
up_train = nn.ConvTranspose2d(1, 1, kernel_size=2, stride=1, padding=1, bias=False)
up_train.weight.data = k

y = up_train(x)
print(y)
print(up_train.weight.data)

tensor([[[[4.]]]], grad_fn=<ConvolutionBackward0>)
tensor([[[[0., 1.],
          [2., 3.]]]])


In [51]:
# With stride 2
up_train = nn.ConvTranspose2d(1, 1, kernel_size=2, stride=2, bias=False)
up_train.weight.data = k

y = up_train(x)
print(y)
print(up_train.weight.data)

tensor([[[[0., 0., 0., 1.],
          [0., 0., 2., 3.],
          [0., 2., 0., 3.],
          [4., 6., 6., 9.]]]], grad_fn=<ConvolutionBackward0>)
tensor([[[[0., 1.],
          [2., 3.]]]])


#### With multiple channels

In [58]:
x = torch.randn((1, 5, 4, 4))
print(x)
print(x.shape)

tensor([[[[-1.0060,  0.9097, -0.5889, -0.0274],
          [ 1.0088, -1.5684,  0.4657,  0.9844],
          [ 0.1656,  0.5367,  0.0853, -0.4395],
          [-0.2649,  0.2611,  0.6810, -0.5670]],

         [[ 0.9798, -0.9821,  0.6488, -0.2658],
          [ 0.1883, -0.6689, -2.2485,  0.7224],
          [-0.8280,  2.5153, -1.0776, -0.4458],
          [-0.3119,  0.4119, -0.2457,  0.4096]],

         [[ 1.3535, -0.2333, -0.3854, -0.0663],
          [-0.3420, -1.7991,  1.5472,  0.1388],
          [-0.6138,  1.3042,  0.4047,  0.4602],
          [-0.7133, -1.0525,  1.7042,  0.6970]],

         [[-0.9859,  1.7812,  0.8766,  1.1159],
          [ 2.2785,  0.8587, -0.4056, -0.2682],
          [ 1.8136,  0.7527, -0.9974,  0.1318],
          [-1.0343,  2.6340, -1.3289,  0.2968]],

         [[ 1.7960, -0.5385, -1.3440, -0.8730],
          [ 0.2722,  0.1482, -0.6506, -1.0737],
          [-1.2181,  0.1634, -1.6605, -0.1715],
          [ 0.5472,  0.3475,  0.3529,  1.1308]]]])
torch.Size([1, 5, 4, 4])


In [61]:
conv = nn.Conv2d(5, 10, kernel_size=3, stride=1)
xx = conv(x)

print(xx)
print(xx.shape)

tensor([[[[ 0.8636,  0.2223],
          [-1.3011,  0.2015]],

         [[ 0.7555, -0.0492],
          [ 1.9143, -0.4791]],

         [[ 0.8971,  0.5829],
          [-0.7113,  0.7700]],

         [[ 0.5645,  0.6223],
          [ 0.3345,  0.0884]],

         [[ 0.7432,  0.2959],
          [ 0.5811,  0.4474]],

         [[-0.6418,  0.2750],
          [ 0.2527,  0.0165]],

         [[ 0.0784,  0.6502],
          [ 0.7480,  0.7623]],

         [[-0.3123,  0.3313],
          [ 0.5403,  0.5952]],

         [[-0.4165,  0.0312],
          [ 0.4829, -0.3776]],

         [[ 0.3107,  0.2262],
          [ 0.8556, -0.3308]]]], grad_fn=<ConvolutionBackward0>)
torch.Size([1, 10, 2, 2])


In [62]:
tconv = nn.ConvTranspose2d(10, 5, kernel_size=3, stride=1)

xxx = tconv(xx)
print(xxx)
print(xxx.shape)

tensor([[[[ 0.1205,  0.1455,  0.2521,  0.4465],
          [ 0.1443, -0.5026,  0.1928,  0.5767],
          [ 0.4991, -0.0160,  0.3185,  0.1993],
          [ 0.2508, -0.3407,  0.0678, -0.1039]],

         [[ 0.5045, -0.0602, -0.0145, -0.0475],
          [-0.2516,  0.1891,  0.1564, -0.1115],
          [-0.0736, -0.3497,  0.0262,  0.0876],
          [ 0.1891,  0.2300, -0.0980,  0.0711]],

         [[-0.2547,  0.0412,  0.4026, -0.1070],
          [-0.1504,  0.0350,  0.0125, -0.1191],
          [ 0.0225, -0.6339,  0.2180,  0.0053],
          [ 0.0312, -0.2097,  0.0811, -0.0035]],

         [[-0.0383,  0.5150,  0.3829,  0.0558],
          [ 0.0063, -0.0029,  0.5743, -0.0067],
          [-0.3632,  0.1734,  0.5067, -0.1406],
          [-0.5034,  0.3834,  0.4566, -0.0983]],

         [[ 0.1559, -0.1056, -0.1607, -0.0518],
          [ 0.3570,  0.4845, -0.0192, -0.0587],
          [-0.1675, -0.0975,  0.2486,  0.0499],
          [ 0.1981,  0.0226, -0.0899,  0.0821]]]],
       grad_fn=<ConvolutionBa

In [63]:
x.shape == xxx.shape

True