In [2]:
import torch

## Create Zero's

In [4]:
torch.zeros((4))

tensor([0., 0., 0., 0.])

In [6]:
zeros = torch.zeros((4, 5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [7]:
zeros + 5

tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])

## Create zeros from other variable shape

In [8]:
rand_matrix = torch.randint(2, 33, (5, 6))
rand_matrix

tensor([[11,  2, 22, 13, 20, 21],
        [14, 17, 29,  4,  5, 21],
        [ 7,  4, 23, 25, 16, 14],
        [13, 23, 25,  3, 22, 28],
        [ 5, 18, 23, 10, 30,  6]])

In [9]:
# create zeros_like from rand_matrix shapes
like_others = torch.zeros_like(rand_matrix)
like_others

tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])

## Create One's

In [10]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [12]:
ones = torch.ones((3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])