In [1]:
import torch

## Tensor Datatype
```
floating -- used for most the deep learning case ---> float32(default), float64, float16
integer -- used for some classification --> int32, int64(default), int8
boolean -- used for masking or indexing ---> bool
complex -- for complex and heavy computation ---> complex64, complex128
```

### Float number

In [3]:
float_number = torch.tensor([1., 2.3, 4.5, 3.3])
float_number.dtype

torch.float32

In [6]:
float_number = torch.tensor([1., 2.3, 4.5, 3.3], dtype=torch.float64)
float_number.dtype

torch.float64

### Interger number

In [7]:
int_number = torch.tensor([1, 2, 3, 4])
int_number.dtype

torch.int64

In [8]:
int_number = torch.tensor([1, 2, 3, 4], dtype=torch.int32)
int_number.dtype

torch.int32

### Boolean

In [9]:
bool_data = torch.tensor([True, False, True, False, False])
bool_data.dtype

torch.bool

## Conversion

In [10]:
# Float to integer
int_num = torch.tensor([1.2, 12.34, 5.5], dtype=torch.int64)
print(int_num)
int_num.dtype

tensor([ 1, 12,  5])


torch.int64

### Another way

In [11]:
int_number = float_number.to(torch.int64)
int_number

tensor([1, 2, 4, 3])

In [12]:
# integer to boolean
bool_data = torch.tensor([0, -2, 3, 4, 0 , 0], dtype=torch.bool)
print(bool_data)
bool_data.dtype

tensor([False,  True,  True,  True, False, False])


torch.bool

In [13]:
# integer to float
float_num = int_num.to(torch.float32)
print(float_num)

tensor([ 1., 12.,  5.])
