In [3]:
import torch

## Tensor Manipulations
- reshape
- slicing
- joining and spliting
- transpose and permutation
- cloning and detaching

### Reshape

In [4]:
org_tensor = torch.arange(12)

print('Before\n', org_tensor)
print('shape', org_tensor.shape)
print('Elements', org_tensor.nelement())
print('-'*30)

# Reshape using reshape function
shaped_ten = org_tensor.reshape((3, 4))

print('After\n', shaped_ten)
print('shape', shaped_ten.shape)
print('Elements', shaped_ten.nelement())

Before
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
shape torch.Size([12])
Elements 12
------------------------------
After
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
shape torch.Size([3, 4])
Elements 12


In [5]:
# view is only used for contiguous memory location
print('Is contiguous?', org_tensor.is_contiguous())
sized_ten = org_tensor.view(2, 6)
print(sized_ten)

Is contiguous? True
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


### Slicing

In [9]:
org_tensor = torch.arange(12)
org_tensor = org_tensor.reshape((4, 3))
org_tensor

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [10]:
# slice 1st row
org_tensor[1]

tensor([3, 4, 5])

In [11]:
# slice 1st column
org_tensor[:, 1]

tensor([ 1,  4,  7, 10])

In [13]:
# slice 2nd row to end, and 1st column to end
org_tensor[2:, 1:]

tensor([[ 7,  8],
        [10, 11]])

### Joining
using cat() and join() functions

cat()
- join tensor row-wise or column-wise
- but not change data dimension

stack()
- join tensor row-wsie or column-wise
- but also change the data dimension

In [16]:
tensor_a = torch.tensor([[1, 2], [4, 5]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# using cat() function
join_tensor_row = torch.cat((tensor_a, tensor_b), dim=0) # Row-wise
print(join_tensor_row)

join_tensor_col = torch.cat((tensor_a, tensor_b), dim=1)
print(join_tensor_col)

tensor([[1, 2],
        [4, 5],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [4, 5, 7, 8]])


In [19]:
# using stack() function
join_tensor_row = torch.stack((tensor_a, tensor_b), dim=0)
print(join_tensor_row)

join_tensor_col = torch.stack((tensor_a, tensor_b), dim=1)
print(join_tensor_col)

tensor([[[1, 2],
         [4, 5]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [5, 6]],

        [[4, 5],
         [7, 8]]])


### Spliting
using chunk() and split() function

chunk() ----> divide the data into same sized of chunks<br>
split() ----> divide the data into specified sized but not same sized

In [29]:
tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Using chunk() function
chunks = torch.chunk(tensor, 2, dim=0) # Row wise
print(chunks)

chunks = torch.chunk(tensor, 2, dim=1) # Column wise
chunks

(tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]), tensor([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]))


(tensor([[ 1,  2],
         [ 5,  6],
         [ 9, 10],
         [13, 14]]),
 tensor([[ 3,  4],
         [ 7,  8],
         [11, 12],
         [15, 16]]))

In [36]:
# Using split() function
splits = torch.split(tensor, 2, 0) # Row wise
print(splits)

splits = torch.split(tensor, 3, 1)
splits

(tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]), tensor([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]))


(tensor([[ 1,  2,  3],
         [ 5,  6,  7],
         [ 9, 10, 11],
         [13, 14, 15]]),
 tensor([[ 4],
         [ 8],
         [12],
         [16]]))

### Transpose

In [40]:
tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

torch.transpose(tensor, 0, 1)

tensor([[ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15],
        [ 4,  8, 12, 16]])

### Permutate

In [43]:
tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]).reshape(-1, 4, 2)

print(tensor)
print(tensor.shape)
# shape always has [0, 1, 2] combination
torch.permute(tensor, (2, 1, 0))

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12],
         [13, 14],
         [15, 16]]])
torch.Size([2, 4, 2])


tensor([[[ 1,  9],
         [ 3, 11],
         [ 5, 13],
         [ 7, 15]],

        [[ 2, 10],
         [ 4, 12],
         [ 6, 14],
         [ 8, 16]]])

### Clone and Detach

In [49]:
tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

tensor_a = tensor # It passes the reference
tensor_a[0, 2] = 12.0
print(tensor)
print(tensor_a)
print('-'*30)

tensor_b = tensor.clone() # Not passes the reference
tensor_b[0, 2] = 20.0
print(tensor)
print(tensor_b)
print('-'*30)

tensor([[ 1,  2, 12,  4],
        [ 5,  6,  7,  8]])
tensor([[ 1,  2, 12,  4],
        [ 5,  6,  7,  8]])
------------------------------
tensor([[ 1,  2, 12,  4],
        [ 5,  6,  7,  8]])
tensor([[ 1,  2, 20,  4],
        [ 5,  6,  7,  8]])
------------------------------


In [52]:
tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=torch.float32, requires_grad=True)

print(tensor)

tensor = tensor.detach() # Remove the computational graps features thats are added by grad
print(tensor)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], requires_grad=True)
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
