In [1]:
import torch

In [2]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]], dtype=torch.float32)

In [3]:
print(matrix.sum())
print(matrix.mean())
print(matrix.median())
print(matrix.min())
print(matrix.max())

tensor(45.)
tensor(5.)
tensor(5.)
tensor(1.)
tensor(9.)


In [6]:
# dim = 0 ---> row (column wise down)
print(matrix.sum(dim=0))
print(matrix.min(dim=0))
print(matrix.max(dim=0))

# dim = 1 ---> column (row wise righ)
print('\n')
print('-'*30)
print(matrix.sum(dim=1))
print(matrix.min(dim=1))
print(matrix.max(dim=1))

tensor([12., 15., 18.])
torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))
torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))


------------------------------
tensor([ 6., 15., 24.])
torch.return_types.min(
values=tensor([1., 4., 7.]),
indices=tensor([0, 0, 0]))
torch.return_types.max(
values=tensor([3., 6., 9.]),
indices=tensor([2, 2, 2]))


In [8]:
matrix.cumsum(0)

tensor([[ 1.,  2.,  3.],
        [ 5.,  7.,  9.],
        [12., 15., 18.]])

In [9]:
matrix.cumprod(0)

tensor([[  1.,   2.,   3.],
        [  4.,  10.,  18.],
        [ 28.,  80., 162.]])